"""SQLAlchemy models for the Macro Dashboard database.

These are the Python-side representation of the tables created by Alembic.
Whenever the migration schema changes, keep these models in sync. Alembic's
autogenerate feature compares these models against the DB to detect drift.

All models use SQLAlchemy 2.0 syntax with Mapped/mapped_column. Type hints
are load-bearing here — SQLAlchemy uses them at runtime for the mapping.
"""

from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from typing import Any

from sqlalchemy import (
    BigInteger,
    Boolean,
    Computed,
    Date,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    SmallInteger,
    String,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.dialects.postgresql import ARRAY, JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    """Declarative base for all ORM models.

    Imported by migrations/env.py so Alembic autogenerate can see all tables.
    """


class Country(Base):
    """One of the tracked countries / currencies.

    Reference data — populated once via scripts/seed_countries.py and rarely
    changes afterwards.
    """

    __tablename__ = "countries"

    code: Mapped[str] = mapped_column(String(2), primary_key=True)
    currency_code: Mapped[str] = mapped_column(String(3), nullable=False)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    central_bank: Mapped[str] = mapped_column(Text, nullable=False)
    cb_inflation_target: Mapped[Decimal | None] = mapped_column(
        Numeric(4, 2), nullable=True
    )
    cb_mandate_type: Mapped[str] = mapped_column(Text, nullable=False)
    timezone: Mapped[str] = mapped_column(Text, nullable=False)

    # Relationships
    indicators: Mapped[list[Indicator]] = relationship(
        "Indicator",
        back_populates="country",
        cascade="all, delete-orphan",
    )

    def __repr__(self) -> str:
        return f"<Country code={self.code!r} currency={self.currency_code!r}>"


class Indicator(Base):
    """A canonicalized indicator definition for one country.

    One row per (canonical_name, country_code). Populated from
    config/indicator_mapping.yaml at seed time, but can be added to
    dynamically when new EODHD event types are encountered.
    """

    __tablename__ = "indicators"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    canonical_name: Mapped[str] = mapped_column(Text, nullable=False)
    display_name: Mapped[str] = mapped_column(Text, nullable=False)
    country_code: Mapped[str] = mapped_column(
        String(2),
        ForeignKey("countries.code", ondelete="RESTRICT"),
        nullable=False,
    )
    primary_category: Mapped[str] = mapped_column(Text, nullable=False)
    secondary_categories: Mapped[list[str]] = mapped_column(
        ARRAY(Text),
        nullable=False,
        server_default="{}",
    )
    comparison: Mapped[str | None] = mapped_column(Text, nullable=True)
    frequency: Mapped[str] = mapped_column(Text, nullable=False)
    unit: Mapped[str | None] = mapped_column(Text, nullable=True)
    is_higher_better_for_currency: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        server_default=text("true"),
    )
    importance: Mapped[int] = mapped_column(
        SmallInteger,
        nullable=False,
        server_default="2",
    )
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    __table_args__ = (
        UniqueConstraint(
            "canonical_name",
            "country_code",
            name="uq_indicators_canonical_country",
        ),
    )

    # Relationships
    country: Mapped[Country] = relationship("Country", back_populates="indicators")
    releases: Mapped[list[IndicatorRelease]] = relationship(
        "IndicatorRelease",
        back_populates="indicator",
        cascade="all, delete-orphan",
    )

    def __repr__(self) -> str:
        return (
            f"<Indicator id={self.id} canonical={self.canonical_name!r} "
            f"country={self.country_code!r}>"
        )


class IndicatorRelease(Base):
    """One release (print) of an indicator, versioned for revision tracking.

    When EODHD revises a value, we insert a new row with the updated value
    and set the previous row's is_latest=False. This preserves the full
    reporting history so backtests can use "as-reported" values and avoid
    look-ahead bias.

    The indicator_id can be NULL when an event arrives for which we have no
    canonical mapping yet (e.g. a new EODHD event type). These rows are
    stored so the data isn't lost, and we can backfill-canonicalize them
    once a mapping is added.

    The 'surprise' column is generated by Postgres: actual - estimate.
    """

    __tablename__ = "indicator_releases"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    indicator_id: Mapped[int | None] = mapped_column(
        Integer,
        ForeignKey("indicators.id", ondelete="CASCADE"),
        nullable=True,
    )
    period: Mapped[str | None] = mapped_column(Text, nullable=True)
    period_start_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    released_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    actual: Mapped[Decimal | None] = mapped_column(Numeric(20, 6), nullable=True)
    previous: Mapped[Decimal | None] = mapped_column(Numeric(20, 6), nullable=True)
    estimate: Mapped[Decimal | None] = mapped_column(Numeric(20, 6), nullable=True)
    change: Mapped[Decimal | None] = mapped_column(Numeric(20, 6), nullable=True)
    change_percentage: Mapped[Decimal | None] = mapped_column(
        Numeric(20, 6), nullable=True
    )
    # Generated column. SQLAlchemy knows not to INSERT or UPDATE it.
    surprise: Mapped[Decimal | None] = mapped_column(
        Numeric(20, 6),
        Computed("actual - estimate", persisted=True),
        nullable=True,
    )
    retrieved_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
    )
    is_latest: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        server_default=text("true"),
    )
    raw_payload: Mapped[dict[str, Any] | None] = mapped_column(
        JSONB, nullable=True
    )

    # Relationships
    indicator: Mapped[Indicator | None] = relationship(
        "Indicator", back_populates="releases"
    )

    def __repr__(self) -> str:
        return (
            f"<IndicatorRelease id={self.id} indicator_id={self.indicator_id} "
            f"period={self.period!r} actual={self.actual} is_latest={self.is_latest}>"
        )


class IngestionRun(Base):
    """Audit log of ingestion runs.

    One row per scheduled run or manual backfill invocation. Powers the
    admin health endpoint (Step 3).
    """

    __tablename__ = "ingestion_runs"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
    )
    finished_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    run_type: Mapped[str] = mapped_column(Text, nullable=False)
    countries_fetched: Mapped[list[str]] = mapped_column(
        ARRAY(Text),
        nullable=False,
        server_default="{}",
    )
    events_inserted: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    events_updated: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    api_calls_used: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    errors: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    status: Mapped[str] = mapped_column(
        Text, nullable=False, server_default="'running'"
    )

    def __repr__(self) -> str:
        return (
            f"<IngestionRun id={self.id} type={self.run_type!r} "
            f"status={self.status!r} started={self.started_at.isoformat()}>"
        )


class User(Base):
    """Dashboard user account with role-based access."""

    __tablename__ = "users"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    email: Mapped[str] = mapped_column(String(255), nullable=False, unique=True)
    display_name: Mapped[str] = mapped_column(Text, nullable=False)
    password_hash: Mapped[str] = mapped_column(Text, nullable=False)
    role: Mapped[str] = mapped_column(String(20), nullable=False, server_default="viewer")
    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        server_default=text("true"),
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
    )
    last_login_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    def __repr__(self) -> str:
        return f"<User id={self.id} email={self.email!r} role={self.role!r}>"


class CorrelationCache(Base):
    """Cached monthly series used by the Correlation Lab."""

    __tablename__ = "correlation_cache"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    pair: Mapped[str] = mapped_column(String(10), nullable=False)
    series_key: Mapped[str] = mapped_column(String(50), nullable=False)
    month: Mapped[date] = mapped_column(Date, nullable=False)
    value: Mapped[Decimal | None] = mapped_column(Numeric(18, 6), nullable=True)
    fetched_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
    )

    __table_args__ = (
        UniqueConstraint("pair", "series_key", "month", name="uq_correlation_cache_series"),
    )

    def __repr__(self) -> str:
        return (
            f"<CorrelationCache pair={self.pair!r} "
            f"series={self.series_key!r} month={self.month.isoformat()}>"
        )


class CBMeeting(Base):
    """Scheduled central-bank policy meeting."""

    __tablename__ = "cb_meetings"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    bank: Mapped[str] = mapped_column(String(10), nullable=False)
    meeting_dt: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    is_official: Mapped[bool | None] = mapped_column(
        Boolean,
        nullable=True,
        server_default=text("true"),
    )

    __table_args__ = (
        UniqueConstraint("bank", "meeting_dt", name="uq_cb_meetings_bank_dt"),
    )

    def __repr__(self) -> str:
        return f"<CBMeeting bank={self.bank!r} meeting_dt={self.meeting_dt.isoformat()}>"


class RateSnapshot(Base):
    """Stored implied-rate snapshot for a bank meeting."""

    __tablename__ = "rate_snapshots"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    bank: Mapped[str] = mapped_column(String(10), nullable=False)
    snapshot_date: Mapped[date] = mapped_column(Date, nullable=False)
    meeting_dt: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    implied_rate: Mapped[Decimal] = mapped_column(Numeric(6, 4), nullable=False)
    cut_prob: Mapped[Decimal | None] = mapped_column(Numeric(5, 4), nullable=True)
    hold_prob: Mapped[Decimal | None] = mapped_column(Numeric(5, 4), nullable=True)
    hike_prob: Mapped[Decimal | None] = mapped_column(Numeric(5, 4), nullable=True)
    delta_bps: Mapped[Decimal | None] = mapped_column(Numeric(7, 2), nullable=True)
    fetched_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        server_default=text("now()"),
    )

    __table_args__ = (
        UniqueConstraint(
            "bank",
            "snapshot_date",
            "meeting_dt",
            name="uq_rate_snapshots_bank_snapshot_meeting",
        ),
    )

    def __repr__(self) -> str:
        return (
            f"<RateSnapshot bank={self.bank!r} snapshot={self.snapshot_date.isoformat()} "
            f"meeting_dt={self.meeting_dt.isoformat()}>"
        )


class CbPolicyReport(Base):
    """AI-analyzed central bank monetary policy statement.

    One row per (bank, meeting_date). Scraped from official CB websites and
    analyzed by OpenAI to extract tone score, outlook directions, and
    retail-trader-friendly summaries.
    """

    __tablename__ = "cb_policy_reports"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    bank: Mapped[str] = mapped_column(String(10), nullable=False)
    meeting_date: Mapped[date] = mapped_column(Date, nullable=False)
    report_type: Mapped[str] = mapped_column(
        String(30), nullable=False, server_default=text("'statement'")
    )
    source_url: Mapped[str | None] = mapped_column(Text, nullable=True)
    source_pdf_url: Mapped[str | None] = mapped_column(Text, nullable=True)
    raw_text: Mapped[str | None] = mapped_column(Text, nullable=True)

    # AI-derived fields (NULL until analyzed)
    tone_score: Mapped[Decimal | None] = mapped_column(Numeric(4, 2), nullable=True)
    tone_label: Mapped[str | None] = mapped_column(String(30), nullable=True)
    inflation_outlook: Mapped[str | None] = mapped_column(String(30), nullable=True)
    inflation_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    growth_outlook: Mapped[str | None] = mapped_column(String(30), nullable=True)
    growth_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    labor_outlook: Mapped[str | None] = mapped_column(String(30), nullable=True)
    labor_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    key_phrases: Mapped[list[str] | None] = mapped_column(ARRAY(Text), nullable=True)
    tone_change_vs_prior: Mapped[str | None] = mapped_column(Text, nullable=True)
    retail_bullets: Mapped[list[str] | None] = mapped_column(ARRAY(Text), nullable=True)
    full_analysis: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)

    analyzed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    scraped_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
    )

    __table_args__ = (
        UniqueConstraint("bank", "meeting_date", name="uq_cb_policy_reports_bank_date"),
    )

    def __repr__(self) -> str:
        return (
            f"<CbPolicyReport bank={self.bank!r} "
            f"meeting_date={self.meeting_date.isoformat()} tone={self.tone_score}>"
        )


class CbPolicyDocument(Base):
    """A manually downloaded or uploaded CB policy PDF with AI analysis.

    One row per (bank, doc_date, doc_type). Stores the full text and all
    AI-derived fields extracted by cb_document_ingester.py.
    """

    __tablename__ = "cb_policy_documents"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    bank: Mapped[str] = mapped_column(String(10), nullable=False)
    doc_type: Mapped[str] = mapped_column(
        String(20), nullable=False, server_default=text("'statement'")
    )
    doc_date: Mapped[date] = mapped_column(Date, nullable=False)
    filename: Mapped[str] = mapped_column(Text, nullable=False)
    file_path: Mapped[str] = mapped_column(Text, nullable=False)
    raw_text: Mapped[str | None] = mapped_column(Text, nullable=True)

    tone_score: Mapped[Decimal | None] = mapped_column(Numeric(4, 2), nullable=True)
    tone_label: Mapped[str | None] = mapped_column(String(30), nullable=True)
    inflation_outlook: Mapped[str | None] = mapped_column(String(30), nullable=True)
    inflation_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    growth_outlook: Mapped[str | None] = mapped_column(String(30), nullable=True)
    growth_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    labor_outlook: Mapped[str | None] = mapped_column(String(30), nullable=True)
    labor_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    key_phrases: Mapped[list[str] | None] = mapped_column(ARRAY(Text), nullable=True)
    tone_change_vs_prior: Mapped[str | None] = mapped_column(Text, nullable=True)
    retail_bullets: Mapped[list[str] | None] = mapped_column(ARRAY(Text), nullable=True)
    full_analysis: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)

    analyzed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
    )

    __table_args__ = (
        UniqueConstraint("bank", "doc_date", "doc_type", name="uq_cb_policy_docs"),
    )

    def __repr__(self) -> str:
        return (
            f"<CbPolicyDocument bank={self.bank!r} doc_date={self.doc_date.isoformat()} "
            f"doc_type={self.doc_type!r} tone={self.tone_score}>"
        )


class CbEconomicProjection(Base):
    """CB economic forecasts extracted from projection documents.

    One row per (bank, projection_date, horizon_label). Populated by
    cb_document_ingester when analyzing projection/MPR documents.
    """

    __tablename__ = "cb_economic_projections"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    bank: Mapped[str] = mapped_column(String(10), nullable=False)
    projection_date: Mapped[date] = mapped_column(Date, nullable=False)
    horizon_label: Mapped[str] = mapped_column(String(30), nullable=False)
    horizon_year: Mapped[int | None] = mapped_column(Integer, nullable=True)
    inflation_forecast: Mapped[Decimal | None] = mapped_column(
        Numeric(6, 3), nullable=True
    )
    gdp_forecast: Mapped[Decimal | None] = mapped_column(Numeric(6, 3), nullable=True)
    unemployment_forecast: Mapped[Decimal | None] = mapped_column(
        Numeric(6, 3), nullable=True
    )
    source_doc_id: Mapped[int | None] = mapped_column(
        BigInteger,
        ForeignKey("cb_policy_documents.id", ondelete="SET NULL"),
        nullable=True,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
    )

    __table_args__ = (
        UniqueConstraint(
            "bank", "projection_date", "horizon_label", name="uq_cb_econ_proj"
        ),
    )

    # Relationships
    source_doc: Mapped[CbPolicyDocument | None] = relationship("CbPolicyDocument")

    def __repr__(self) -> str:
        return (
            f"<CbEconomicProjection bank={self.bank!r} "
            f"proj_date={self.projection_date.isoformat()} "
            f"horizon={self.horizon_label!r}>"
        )


class OISCache(Base):
    """Cached OIS curve point."""

    __tablename__ = "ois_cache"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    bank: Mapped[str] = mapped_column(String(10), nullable=False)
    curve_date: Mapped[date] = mapped_column(Date, nullable=False)
    tenor_days: Mapped[int] = mapped_column(Integer, nullable=False)
    rate: Mapped[Decimal] = mapped_column(Numeric(8, 6), nullable=False)
    source: Mapped[str | None] = mapped_column(String(50), nullable=True)
    fetched_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        server_default=text("now()"),
    )

    __table_args__ = (
        UniqueConstraint(
            "bank",
            "curve_date",
            "tenor_days",
            name="uq_ois_cache_bank_curve_tenor",
        ),
    )

    def __repr__(self) -> str:
        return (
            f"<OISCache bank={self.bank!r} curve={self.curve_date.isoformat()} "
            f"tenor_days={self.tenor_days}>"
        )


class EventReactionNote(Base):
    """A manually-logged news event, for building the event-trading dataset.

    One row per indicator_release the user chose to log. forecast/actual are
    entered by hand (the calendar's own estimate/actual may not be fresh at
    release time); previous_value is captured from the prior release so it's
    frozen even if history gets revised later. ai_interpretation is generated
    on demand and then hand-edited — never treated as authoritative.
    """

    __tablename__ = "event_reaction_notes"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    indicator_release_id: Mapped[int] = mapped_column(
        BigInteger,
        ForeignKey("indicator_releases.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
    )
    forecast_value: Mapped[Decimal | None] = mapped_column(Numeric(20, 6), nullable=True)
    actual_value: Mapped[Decimal | None] = mapped_column(Numeric(20, 6), nullable=True)
    previous_value: Mapped[Decimal | None] = mapped_column(Numeric(20, 6), nullable=True)
    manual_notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    ai_interpretation: Mapped[str | None] = mapped_column(Text, nullable=True)
    ai_generated_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )

    # Relationships
    indicator_release: Mapped[IndicatorRelease] = relationship("IndicatorRelease")
    price_reactions: Mapped[list[EventPriceReaction]] = relationship(
        "EventPriceReaction",
        back_populates="event",
        cascade="all, delete-orphan",
    )

    def __repr__(self) -> str:
        return f"<EventReactionNote id={self.id} release_id={self.indicator_release_id}>"


class EventPriceReaction(Base):
    """One (instrument, horizon) price cell for a logged event.

    raw_price is pasted by hand off a chart. pip_change/pct_change are
    computed server-side from the event's t0 price using each instrument's
    pip convention, so later aggregation queries never have to redo that math.
    """

    __tablename__ = "event_price_reactions"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    event_id: Mapped[int] = mapped_column(
        BigInteger,
        ForeignKey("event_reaction_notes.id", ondelete="CASCADE"),
        nullable=False,
    )
    instrument: Mapped[str] = mapped_column(String(10), nullable=False)
    horizon: Mapped[str] = mapped_column(String(4), nullable=False)
    raw_price: Mapped[Decimal | None] = mapped_column(Numeric(12, 6), nullable=True)
    pip_change: Mapped[Decimal | None] = mapped_column(Numeric(12, 2), nullable=True)
    pct_change: Mapped[Decimal | None] = mapped_column(Numeric(10, 4), nullable=True)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )

    __table_args__ = (
        UniqueConstraint(
            "event_id", "instrument", "horizon", name="uq_event_price_reactions_cell"
        ),
    )

    # Relationships
    event: Mapped[EventReactionNote] = relationship(
        "EventReactionNote", back_populates="price_reactions"
    )

    def __repr__(self) -> str:
        return (
            f"<EventPriceReaction event_id={self.event_id} "
            f"instrument={self.instrument!r} horizon={self.horizon!r}>"
        )


class RawNews(Base):
    """Unprocessed news item exactly as fetched from a source."""

    __tablename__ = "raw_news"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    source: Mapped[str] = mapped_column(Text, nullable=False)
    source_category: Mapped[str | None] = mapped_column(Text, nullable=True)
    title: Mapped[str] = mapped_column(Text, nullable=False)
    body: Mapped[str | None] = mapped_column(Text, nullable=True)
    url: Mapped[str | None] = mapped_column(Text, nullable=True)
    published_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    fetched_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )
    raw_payload: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    is_gated_relevant: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("false")
    )

    __table_args__ = (
        Index("ix_raw_news_published_at", "published_at"),
    )

    enriched_items: Mapped[list[EnrichedNews]] = relationship(
        "EnrichedNews",
        back_populates="raw_news",
        cascade="all, delete-orphan",
    )

    def __repr__(self) -> str:
        return f"<RawNews id={self.id} source={self.source!r} published={self.published_at}>"


class EnrichedNews(Base):
    """AI/enrichment output derived from a raw news item."""

    __tablename__ = "enriched_news"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    raw_news_id: Mapped[int] = mapped_column(
        BigInteger,
        ForeignKey("raw_news.id", ondelete="CASCADE"),
        nullable=False,
    )
    tier: Mapped[str] = mapped_column(Text, nullable=False)
    country: Mapped[str | None] = mapped_column(Text, nullable=True)
    surprise_factor: Mapped[str | None] = mapped_column(Text, nullable=True)
    currency_impact: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    inflation_impact: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    employment_growth_impact: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    gold_analysis: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    historical_analog: Mapped[str | None] = mapped_column(Text, nullable=True)
    invalidation: Mapped[str | None] = mapped_column(Text, nullable=True)
    confidence: Mapped[int | None] = mapped_column(Integer, nullable=True)
    market_context: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    contains_unverified_entity: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("false")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )

    __table_args__ = (
        Index("ix_enriched_news_tier", "tier"),
        Index("ix_enriched_news_raw_news_id", "raw_news_id"),
        Index(
            "ix_enriched_news_gold_net_direction",
            text("(gold_analysis ->> 'net_direction')"),
        ),
    )

    raw_news: Mapped[RawNews] = relationship("RawNews", back_populates="enriched_items")
    price_snapshots: Mapped[list[PriceSnapshot]] = relationship(
        "PriceSnapshot",
        back_populates="enriched_news",
        cascade="all, delete-orphan",
    )

    def __repr__(self) -> str:
        return f"<EnrichedNews id={self.id} raw_news_id={self.raw_news_id} tier={self.tier!r}>"


class PriceSnapshot(Base):
    """Price capture around an enriched news item."""

    __tablename__ = "price_snapshots"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    enriched_news_id: Mapped[int] = mapped_column(
        BigInteger,
        ForeignKey("enriched_news.id", ondelete="CASCADE"),
        nullable=False,
    )
    instrument: Mapped[str] = mapped_column(String(30), nullable=False)
    snapshot_type: Mapped[str] = mapped_column(
        Enum(
            "immediate",
            "15m",
            "1h",
            "4h",
            "eod",
            name="price_snapshot_type",
        ),
        nullable=False,
    )
    scheduled_for: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    captured_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    price: Mapped[Decimal] = mapped_column(Numeric(20, 6), nullable=False)
    price_change_from_immediate_pct: Mapped[Decimal | None] = mapped_column(
        Numeric(10, 4), nullable=True
    )

    __table_args__ = (
        Index("ix_price_snapshots_enriched_news_id", "enriched_news_id"),
        Index("ix_price_snapshots_instrument_snapshot_type", "instrument", "snapshot_type"),
    )

    enriched_news: Mapped[EnrichedNews] = relationship(
        "EnrichedNews", back_populates="price_snapshots"
    )

    def __repr__(self) -> str:
        return (
            f"<PriceSnapshot enriched_news_id={self.enriched_news_id} "
            f"instrument={self.instrument!r} type={self.snapshot_type!r}>"
        )


class SourceHealth(Base):
    """Latest ingestion health snapshot for a news source."""

    __tablename__ = "source_health"

    source_name: Mapped[str] = mapped_column(Text, primary_key=True)
    last_item_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    last_checked_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )
    is_healthy: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("true")
    )

    def __repr__(self) -> str:
        return (
            f"<SourceHealth source={self.source_name!r} "
            f"healthy={self.is_healthy} checked={self.last_checked_at}>"
        )
