"""Visual artifact extraction for Knowledge Bank PDFs.

Figures and tables are derived artifacts. Original PDFs remain untouched, and
the extracted files can be deleted/regenerated by version.
"""

from __future__ import annotations

import hashlib
import re
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.models import (
    KnowledgeDocumentPage,
    KnowledgeFigure,
    KnowledgeSourceDocument,
    KnowledgeSourceFile,
    KnowledgeTable,
)

VISUAL_EXTRACTION_VERSION = "pymupdf-visual-v1"
TABLE_EXTRACTION_VERSION = "text-table-heuristic-v1"
VISUAL_ARTIFACT_DIR = Path("data/knowledge_bank/visuals")
MIN_IMAGE_BYTES = 8_000
MIN_IMAGE_WIDTH = 120
MIN_IMAGE_HEIGHT = 80
MARKET_VISUAL_TERMS = {
    "aud", "bcom", "bitcoin", "boj", "bond", "cad", "chart", "chf",
    "commodity", "cpi", "crypto", "curve", "dollar", "equity", "eur",
    "fed", "fomc", "fx", "gbp", "gold", "inflation", "jolts", "jpy",
    "krw", "labor", "market", "move", "nfp", "oil", "positioning",
    "qqq", "rate", "reaction", "rsi", "silver", "spcx", "stock",
    "tariff", "usd", "vol", "xag", "xau", "yield",
}
VISUAL_EVIDENCE_TERMS = {"chart", "exhibit", "figure", "graph", "source:", "table"}
NON_MARKET_VISUAL_TERMS = {
    "album", "anime", "casino", "comic", "derby picks", "fanbois",
    "ghost ship", "meme", "movie", "music", "roulette", "song",
    "thanks for reading", "youtube",
}


@dataclass
class VisualExtractionSummary:
    documents_seen: int = 0
    documents_processed: int = 0
    documents_skipped: int = 0
    figures_created: int = 0
    figures_existing: int = 0
    figures_ignored: int = 0
    existing_figures_reclassified: int = 0
    tables_created: int = 0
    tables_existing: int = 0
    failed: int = 0
    warnings: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True)
class FigureCandidate:
    page_number: int
    figure_index: int
    image_hash: str
    image_bytes: bytes
    image_format: str
    width_px: int | None
    height_px: int | None
    bbox: dict[str, float] | None
    nearby_text: str | None
    caption: str | None


@dataclass(frozen=True)
class TableCandidate:
    page_number: int
    table_index: int
    table_hash: str
    raw_text: str
    cleaned_text: str
    caption: str | None
    structured_rows: list[list[str]]


async def extract_visual_artifacts(
    session: AsyncSession,
    output_dir: Path = VISUAL_ARTIFACT_DIR,
    limit: int | None = None,
    document_id: int | None = None,
    progress: bool = False,
) -> VisualExtractionSummary:
    summary = VisualExtractionSummary()
    query = select(KnowledgeSourceDocument).order_by(KnowledgeSourceDocument.id.asc())
    if document_id is not None:
        query = query.where(KnowledgeSourceDocument.id == document_id)
    if limit:
        query = query.limit(limit)
    documents = list((await session.execute(query)).scalars().all())
    summary.documents_seen = len(documents)

    for document in documents:
        if progress:
            print(f"Processing document {document.id}: {document.original_filename}", flush=True)
        source_path = await _source_path_for_document(session, document.id)
        if source_path is None:
            summary.documents_skipped += 1
            summary.warnings.append(f"No source file path for document {document.id}.")
            continue
        try:
            document_summary = await extract_visual_artifacts_for_document(
                session=session,
                document=document,
                source_path=source_path,
                output_dir=output_dir,
            )
        except Exception as exc:
            summary.failed += 1
            summary.warnings.append(f"{document.original_filename}: visual extraction failed: {exc}")
            continue
        summary.documents_processed += 1
        summary.figures_created += document_summary.figures_created
        summary.figures_existing += document_summary.figures_existing
        summary.figures_ignored += document_summary.figures_ignored
        summary.tables_created += document_summary.tables_created
        summary.tables_existing += document_summary.tables_existing
        summary.warnings.extend(document_summary.warnings)

    return summary


async def extract_visual_artifacts_for_document(
    session: AsyncSession,
    document: KnowledgeSourceDocument,
    source_path: Path,
    output_dir: Path = VISUAL_ARTIFACT_DIR,
) -> VisualExtractionSummary:
    summary = VisualExtractionSummary(documents_seen=1)
    if not source_path.exists():
        summary.documents_skipped = 1
        summary.warnings.append(f"Missing source file: {source_path}")
        return summary

    figure_candidates = extract_figure_candidates(source_path)
    for candidate in figure_candidates:
        decision, reason = classify_figure_candidate(candidate)
        if decision == "ignore":
            summary.figures_ignored += 1
            continue
        existing = await _figure_by_hash(session, document.id, candidate.image_hash)
        if existing:
            summary.figures_existing += 1
            continue
        artifact_path = write_figure_artifact(
            output_dir=output_dir,
            document_id=document.id,
            image_hash=candidate.image_hash,
            image_format=candidate.image_format,
            image_bytes=candidate.image_bytes,
        )
        session.add(
            KnowledgeFigure(
                document_id=document.id,
                page_number=candidate.page_number,
                figure_index=candidate.figure_index,
                image_hash=candidate.image_hash,
                artifact_path=str(artifact_path),
                image_format=candidate.image_format,
                width_px=candidate.width_px,
                height_px=candidate.height_px,
                bbox=candidate.bbox,
                nearby_text=candidate.nearby_text,
                caption=candidate.caption,
                extraction_method=VISUAL_EXTRACTION_VERSION,
                interpretation_status="pending" if decision == "keep" else "needs_visual_review",
                warnings=[reason] if reason else None,
            )
        )
        summary.figures_created += 1

    pages = list(
        (
            await session.execute(
                select(KnowledgeDocumentPage)
                .where(KnowledgeDocumentPage.document_id == document.id)
                .order_by(KnowledgeDocumentPage.page_number.asc())
            )
        ).scalars().all()
    )
    table_candidates = detect_table_candidates_from_pages(pages)
    for candidate in table_candidates:
        existing = await _table_by_hash(session, document.id, candidate.table_hash)
        if existing:
            summary.tables_existing += 1
            continue
        session.add(
            KnowledgeTable(
                document_id=document.id,
                page_number=candidate.page_number,
                table_index=candidate.table_index,
                table_hash=candidate.table_hash,
                caption=candidate.caption,
                raw_text=candidate.raw_text,
                cleaned_text=candidate.cleaned_text,
                structured_rows=candidate.structured_rows,
                extraction_method=TABLE_EXTRACTION_VERSION,
                interpretation_status="pending",
            )
        )
        summary.tables_created += 1
    return summary


async def reclassify_existing_figures(session: AsyncSession) -> VisualExtractionSummary:
    summary = VisualExtractionSummary()
    figures = list((await session.execute(select(KnowledgeFigure))).scalars().all())
    summary.documents_seen = len({figure.document_id for figure in figures})
    for figure in figures:
        decision, reason = classify_visual_metadata(
            width_px=figure.width_px,
            height_px=figure.height_px,
            nearby_text=figure.nearby_text,
            caption=figure.caption,
        )
        next_status = {
            "ignore": "ignored_non_market_visual",
            "review": "needs_visual_review",
            "keep": "pending",
        }[decision]
        if figure.interpretation_status != next_status:
            figure.interpretation_status = next_status
            figure.warnings = [reason] if reason else figure.warnings
            figure.updated_at = datetime.now(timezone.utc)
            summary.existing_figures_reclassified += 1
        if decision == "ignore":
            summary.figures_ignored += 1
    return summary


def extract_figure_candidates(source_path: Path) -> list[FigureCandidate]:
    try:
        import pymupdf
    except ImportError as exc:
        try:
            import fitz as pymupdf
        except ImportError:
            raise RuntimeError("Install PyMuPDF to extract visual PDF artifacts.") from exc

    candidates: list[FigureCandidate] = []
    with pymupdf.open(source_path) as doc:
        seen_document_hashes: set[str] = set()
        for page_index, page in enumerate(doc, start=1):
            page_text = page.get_text("text") or ""
            figure_index = 0
            for image in page.get_images(full=True):
                xref = image[0]
                image_info = doc.extract_image(xref)
                image_bytes = image_info.get("image") or b""
                image_hash = sha256_bytes(image_bytes)
                if image_hash in seen_document_hashes:
                    continue
                seen_document_hashes.add(image_hash)
                width_px = int(image_info.get("width") or 0) or None
                height_px = int(image_info.get("height") or 0) or None
                if not _image_is_large_enough(image_bytes, width_px, height_px):
                    continue
                figure_index += 1
                bbox = _image_bbox(page, xref)
                nearby_text = surrounding_text(page_text)
                candidates.append(
                    FigureCandidate(
                        page_number=page_index,
                        figure_index=figure_index,
                        image_hash=image_hash,
                        image_bytes=image_bytes,
                        image_format=str(image_info.get("ext") or "bin").lower(),
                        width_px=width_px,
                        height_px=height_px,
                        bbox=bbox,
                        nearby_text=nearby_text,
                        caption=infer_caption(page_text),
                    )
                )
    return candidates


def detect_table_candidates_from_pages(
    pages: list[KnowledgeDocumentPage],
) -> list[TableCandidate]:
    candidates: list[TableCandidate] = []
    for page in pages:
        text = page.cleaned_text or page.raw_text or ""
        blocks = detect_table_blocks(text)
        for index, block in enumerate(blocks, start=1):
            rows = parse_table_rows(block)
            table_hash = sha256_text(f"{page.page_number}\n{block}")
            candidates.append(
                TableCandidate(
                    page_number=page.page_number,
                    table_index=index,
                    table_hash=table_hash,
                    raw_text=block,
                    cleaned_text=block,
                    caption=infer_caption(text),
                    structured_rows=rows,
                )
            )
    return candidates


def detect_table_blocks(text: str) -> list[str]:
    lines = [line.strip() for line in text.splitlines()]
    table_lines: list[str] = []
    blocks: list[str] = []
    for line in lines:
        if is_table_like_line(line):
            table_lines.append(line)
            continue
        if len(table_lines) >= 3:
            blocks.append("\n".join(table_lines))
        table_lines = []
    if len(table_lines) >= 3:
        blocks.append("\n".join(table_lines))
    return blocks


def is_table_like_line(line: str) -> bool:
    if len(line) < 12:
        return False
    number_count = len(re.findall(r"[-+]?\d+(?:\.\d+)?%?", line))
    has_spacing = bool(re.search(r"\s{2,}", line))
    has_delimiter = "|" in line or "\t" in line
    return number_count >= 2 and (has_spacing or has_delimiter)


def classify_figure_candidate(candidate: FigureCandidate) -> tuple[str, str | None]:
    return classify_visual_metadata(
        width_px=candidate.width_px,
        height_px=candidate.height_px,
        nearby_text=candidate.nearby_text,
        caption=candidate.caption,
    )


def classify_visual_metadata(
    width_px: int | None,
    height_px: int | None,
    nearby_text: str | None,
    caption: str | None,
) -> tuple[str, str | None]:
    text = f"{caption or ''} {nearby_text or ''}".lower()
    if width_px and height_px and (width_px < MIN_IMAGE_WIDTH or height_px < MIN_IMAGE_HEIGHT):
        return "ignore", "ignored: small decorative image"
    if any(term in text for term in VISUAL_EVIDENCE_TERMS):
        return "keep", None
    market_hits = sum(
        1
        for term in MARKET_VISUAL_TERMS
        if re.search(rf"\b{re.escape(term)}\b", text)
    )
    non_market_hits = sum(1 for term in NON_MARKET_VISUAL_TERMS if term in text)
    if market_hits >= 3 and non_market_hits == 0:
        return "keep", None
    if market_hits >= 2:
        return "review", "review: market context present but visual may be illustrative"
    if non_market_hits > 0:
        return "ignore", "ignored: likely illustrative/non-market image"
    return "ignore", "ignored: no market/chart/table context near image"


def parse_table_rows(block: str) -> list[list[str]]:
    rows: list[list[str]] = []
    for line in block.splitlines():
        if "|" in line:
            cells = [cell.strip() for cell in line.split("|")]
        elif "\t" in line:
            cells = [cell.strip() for cell in line.split("\t")]
        else:
            cells = [cell.strip() for cell in re.split(r"\s{2,}", line)]
        rows.append([cell for cell in cells if cell])
    return rows


def write_figure_artifact(
    output_dir: Path,
    document_id: int,
    image_hash: str,
    image_format: str,
    image_bytes: bytes,
) -> Path:
    safe_format = re.sub(r"[^a-z0-9]+", "", image_format.lower()) or "bin"
    target_dir = output_dir / str(document_id)
    target_dir.mkdir(parents=True, exist_ok=True)
    target = target_dir / f"{image_hash}.{safe_format}"
    if not target.exists():
        target.write_bytes(image_bytes)
    return target


def format_visual_summary(summary: VisualExtractionSummary) -> str:
    data = summary.to_dict()
    labels = {
        "documents_seen": "Documents seen",
        "documents_processed": "Documents processed",
        "documents_skipped": "Documents skipped",
        "figures_created": "Figures created",
        "figures_existing": "Figures existing",
        "figures_ignored": "Figures ignored",
        "existing_figures_reclassified": "Existing figures reclassified",
        "tables_created": "Tables created",
        "tables_existing": "Tables existing",
        "failed": "Failed",
    }
    lines = [f"{label}: {data[key]}" for key, label in labels.items()]
    if summary.warnings:
        lines.append("Warnings:")
        lines.extend(f"- {warning}" for warning in summary.warnings)
    return "\n".join(lines)


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def surrounding_text(page_text: str, limit: int = 1400) -> str:
    return " ".join(page_text.split())[:limit] or ""


def infer_caption(page_text: str) -> str | None:
    for line in page_text.splitlines():
        cleaned = " ".join(line.split())
        if not cleaned:
            continue
        if re.search(r"\b(chart|figure|table|source:|exhibit)\b", cleaned, re.I):
            return cleaned[:300]
    return None


async def _source_path_for_document(
    session: AsyncSession,
    document_id: int,
) -> Path | None:
    result = await session.execute(
        select(KnowledgeSourceFile)
        .where(
            KnowledgeSourceFile.document_id == document_id,
            KnowledgeSourceFile.is_duplicate.is_(False),
        )
        .order_by(KnowledgeSourceFile.id.asc())
    )
    source_file = result.scalar_one_or_none()
    if source_file is None:
        return None
    return Path(source_file.original_path)


async def _figure_by_hash(
    session: AsyncSession,
    document_id: int,
    image_hash: str,
) -> KnowledgeFigure | None:
    result = await session.execute(
        select(KnowledgeFigure).where(
            KnowledgeFigure.document_id == document_id,
            KnowledgeFigure.image_hash == image_hash,
        )
    )
    return result.scalar_one_or_none()


async def _table_by_hash(
    session: AsyncSession,
    document_id: int,
    table_hash: str,
) -> KnowledgeTable | None:
    result = await session.execute(
        select(KnowledgeTable).where(
            KnowledgeTable.document_id == document_id,
            KnowledgeTable.table_hash == table_hash,
        )
    )
    return result.scalar_one_or_none()


def _image_is_large_enough(
    image_bytes: bytes,
    width_px: int | None,
    height_px: int | None,
) -> bool:
    if len(image_bytes) < MIN_IMAGE_BYTES:
        return False
    if width_px is not None and width_px < MIN_IMAGE_WIDTH:
        return False
    if height_px is not None and height_px < MIN_IMAGE_HEIGHT:
        return False
    return True


def _image_bbox(page: Any, xref: int) -> dict[str, float] | None:
    try:
        rects = page.get_image_rects(xref)
    except Exception:
        return None
    if not rects:
        return None
    rect = rects[0]
    return {
        "x0": round(float(rect.x0), 2),
        "y0": round(float(rect.y0), 2),
        "x1": round(float(rect.x1), 2),
        "y1": round(float(rect.y1), 2),
    }
